from django.urls import path
from . import views



urlpatterns = [
    path('', views.home_redirect, name='home'),
    path('dashboard', views.dashboard, name='dashboard'),
    path('student-dashboard/', views.student_dashboard, name='student_dashboard'),
    path('teacher-dashboard/', views.teacher_dashboard, name='teacher_dashboard'),
    path('student_list',views.student_list,name='student_list'),
    path('user_list/',views.user_list,name='user_list'),
    path('updateRole/<int:pk>/', views.user_update_role, name='user_update_role'),
    path('deleteUser/<int:pk>/', views.user_delete, name='user_delete'),
    path('edit/<int:pk>/', views.student_edit, name='student_edit'),
    path('students/delete/<int:pk>/', views.student_delete, name='student_delete'),
    path("index/", views.index, name="index"),
    path('new/', views.student_create, name= 'student_create'),
    path('fee_management/', views.fee_management, name='fee_management'),
    path("add_teacher/", views.teacher_create, name="teacher_create"),
    path('teacherlist', views.teacher_list,name='teacher_list'),
    path('edit-teacher/<int:pk>/', views.teacher_edit, name='teacher_edit'), 
    path("teacher/delete/<int:pk>/", views.teacher_delete, name="teacher_delete"),
    path("send-lesson/", views.send_lesson, name="send-lesson"),
    path('lessons/', views.lesson_list, name='lesson_list'),
    path('lesson/<int:pk>/update/', views.lesson_update, name='lesson_update'),
    path('lesson/<int:pk>/delete/', views.lesson_delete, name='lesson_delete'),
    path('batches/create/', views.create_batch, name='create_batch'),
    path('batches/', views.batch_list, name='batch_list'),
    path('batches/edit/<int:batch_id>/', views.batch_edit, name='batch_edit'),
    path('batches/delete/<int:batch_id>/', views.batch_delete, name='batch_delete'),
    # urls.py
    path('ajax/get-batch-students/', views.get_batch_students, name='get_batch_students'),
    path('ajax/get-batch-teachers/', views.get_batch_teachers, name='get_batch_teachers'),

    path('courses/', views.course_list, name='course_list'),
    path('courses/new/', views.course_create, name='course_create'),
   # path('enrollments/', views.enrollment_list, name='enrollment_list'),
    path('enrollments/new/', views.enrollment_create, name='enrollment_create'),
    path('enrollments/', views.enrollment_list, name = 'enrollments'),
     path('enrollment/<int:enrollment_id>/edit/', views.enrollment_edit, name='enrollment_edit'),
    path('enrollment/<int:enrollment_id>/delete/', views.enrollment_delete, name='enrollment_delete'),
      path('courses/edit/<int:course_id>/', views.edit_course, name='edit_course'),
    path('courses/delete/<int:course_id>/', views.delete_course, name='delete_course'),
    path("dashboard", views.dashboard, name="dashboard"),
  #  path('forms/basic_elements/', views.basic_elements, name='basic_elements'),
    path('buttons/', views.buttons, name='buttons'),
    path('course-fee/<int:batch_id>/', views.batch_fee, name='batch_fee'),
    path('dropdowns/', views.dropdowns, name='dropdowns'),
    path('typography/', views.typography, name='typography'),
    path('add_course/', views.add_course, name='add_course'),
    path('forms/', views.student_create, name='basic_elements'),
    path('charts/', views.charts, name='charts'),
    path('tables/', views.tables, name='tables'),
    path('blank-page/', views.blank_page, name='blank_page'),
    path('login/', views.login_user, name='login'),
    path('register/', views.register, name='register'),
    path('error-404/', views.error_404, name='error_404'),
    path('error-500/', views.error_500, name='error_500'),
    path('settings/', views.settings, name='settings'),
    path('tour/', views.tour, name='tour'),
    path('logout/', views.logout_view, name='logout'),
    path('search/', views.search, name='search'),
    path('reports/pdf/', views.report_pdf, name='report_pdf'),
    path('reports/excel/', views.report_excel, name='report_excel'),
    path('reports/doc/', views.report_doc, name='report_doc'),
    path('projects/view/', views.view_project, name='view_project'),
    path('projects/edit/', views.edit_project, name='edit_project'),
    path('language/ar/', views.language_ar, name='language_ar'),
    path('language/en/', views.language_en, name='language_en'),
    path('inbox/', views.inbox, name='inbox'),
    path('profile/', views.profile, name='profile'),
    path('lock-account/', views.lock_account, name='lock_account'),
    path('messages/', views.messages, name='messages'),
    path('message/detail/', views.message_detail, name='message_detail'),
    path('notifications/', views.notifications, name='notifications'),
    path('notification/detail/', views.notification_detail, name='notification_detail'),
]
