# Generated by Django 5.2.5 on 2025-08-20 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_record', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='fees',
        ),
        migrations.RemoveField(
            model_name='enrollment',
            name='start_date',
        ),
        migrations.AddField(
            model_name='batch',
            name='fee',
            field=models.PositiveBigIntegerField(default=200),
            preserve_default=False,
        ),
    ]
