# Generated by Django 5.2.5 on 2025-08-21 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_record', '0003_alter_lesson_options_lesson_batch_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='fee_type',
            field=models.CharField(choices=[('one_time', 'One-time'), ('installment', 'Installment'), ('custom', 'Custom')], default='one_time', max_length=20),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='paid_amount',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='pending_amount',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
