# Generated by Django 5.2.5 on 2025-08-22 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_record', '0005_alter_enrollment_unique_together_installment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='installment',
            name='order',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='installment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('partial', 'Partially Paid'), ('paid', 'Paid')], default='pending', max_length=20),
        ),
    ]
