# Generated by Django 5.2.5 on 2025-08-22 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_record', '0006_installment_order_alter_installment_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='installment',
            name='order',
        ),
        migrations.AlterField(
            model_name='installment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid')], max_length=20),
        ),
    ]
