# Generated by Django 5.2.5 on 2025-08-25 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_record', '0007_remove_installment_order_alter_installment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='installment',
            name='paid_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
